---
title: 應用Python在投資上的基本構想-1
author: SC
date: '2020-07-19'
slug: concept-1
categories:
  - Stock
tags:
  - Strategy
---

# 投資分析種類

想藉由投資股票賺錢，基本上期望購買的股票價格會漲，然後買出獲利換現金。換句話說，在股票市場上的交易行為，就是在預測(或者是賭？)這些股票會不會漲。判斷股票漲跌的主流方法有兩種:

1. 基本分析
2. 技術分析

# 基本分析

根據維基百科，基本分析為"是一種證券或股票估價的方法，利用財務分析和經濟學上的研究來評估企業價值或預測證券（如股票或債券等）價值的走勢"。所謂財務分析和經濟學研究的目的，當然檢視企業到底混得好不好。混得好的企業，以後股價就會漲，買下去就對了。

# 技術分析

相對基本分析，維基上對技術分析的定義為"是指研究過去金融市場的資訊（主要是經由使用圖表）來預測價格的趨勢與決定投資的策略"。和技術分析最大的差別在於，技術分析並不在意公司到底混得好不好，只要數據上顯示這間公司的股票很有可能會漲，就買下去吧。畢竟絕大多數人買股票目的也只是賺錢，至於公司體質到底好不好，那是另外一回事。

# 超天真(aka無知？)投資想法！

即使是今天才想開始投資的新韭菜如我，也知道關於技術分析和投資分析哪種流派比較有效這種屬於哲學層次的問題，是不會有簡單明確的答案。就個人而言，如果硬要選一邊的話，我還是會站到基本分析的那一邊，因為這樣感覺世界會比較和平。但現實不可能如此簡單，第一財務資訊是可以美化甚至是做假的，公開的財務資訊不見得是百分百可信的。再來即使所有財務資訊都是100%可信，市場瞬息萬變，今天混得好的公司下個月會不會順風順水，同樣是未知數。更現實一點，用來分析一間公司體質的財務指標多到令人眼花撩亂，如果要做全方位的分析，光是研究一間公司的時間恐怕就已經難以估計了，更何況市場上有數不清的公司，如果研究完再做投資決定的話，那可能一輩子也不用投資了。

相對於基本分析，技術分析的優勢在於單純以數據做判斷，因此可以迴避各種人的感情因素。人畢竟是有感情的動物，對一間公司了解越深，越可能對其產生好感，搞不好還會單戀這間公司，這對買賣這種不講感情的世界可不是好事。但技術分析和基本分析的共同問題是，用來做技術分析的指標實在太多了。加上技術分析基本上不在意公司的體質，只用市場資訊(絕大多數是畫線做圖)做判斷，很容易變成看圖說故事大賽。人類天生熱愛聽各種故事，因此也發展出編絕佳的編故事能力，權力遊戲第八季中的布蘭就是因為這種愛聽故事的天性最後才坐上王座的(離題）。不難想像，關於每個在走勢圖上狂飆的個股，就算造成狂漲的理由單純只是內線交易之類，投資老師們也是可以編出個關於這支股票從符合哪種技術指標的故事，或甚至是創造一個新技術指標來說故事。

# 應該是所有人都知道的策略(?)

在一個小韭菜的腦中，理想的情景自然是投資人可以找到真正體質健全且發展良好的公司，然後在公司股價顯示出要上漲的趨勢時，大家都快樂的購入該公司的股票，然後一起發大財，人人都過著幸福美滿的日子，世界從此和平，直到外星人侵略或使徒出現為止。

新手韭菜總是有著跟實力不成正比的自信心(達克效應, aka DK effect)， 我的目標當然也是如此天真且美好。就是先用基本分析指標篩選出體質良好的公司，然後再利用技術分析指標決定每次交易的標的。